### ISSUE TITLE
Upgrade min python version?

### ISSUE THREAD

**Issue by marctorsoc** [tpietruszka/rate_limited#4]
I see the min Python version is 3.8. Maybe upgrade to 3.9 - 3.10?

See https://devguide.python.org/versions/

3.8 will be soon at end of life. Plus, type-hinting will be native if >=3.9 :)

**Comment by tpietruszka** [comment]
I was aiming for max compatibility. Switching to built-in typehints would be nice and then 3.9 requirement would be resaonable, but I woudn't bump the requirements just for the sake of it
